# Generated by Django 5.0.2 on 2025-04-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_alter_article_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='urlToImage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
